/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Example API
 * This is a sample server celler server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllerMessage
 */
export interface ControllerMessage {
    /**
     * 
     * @type {string}
     * @memberof ControllerMessage
     */
    message?: string;
}

/**
 * Check if a given object implements the ControllerMessage interface.
 */
export function instanceOfControllerMessage(value: object): value is ControllerMessage {
    return true;
}

export function ControllerMessageFromJSON(json: any): ControllerMessage {
    return ControllerMessageFromJSONTyped(json, false);
}

export function ControllerMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllerMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ControllerMessageToJSON(json: any): ControllerMessage {
    return ControllerMessageToJSONTyped(json, false);
}

export function ControllerMessageToJSONTyped(value?: ControllerMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

