/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Example API
 * This is a sample server celler server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HttputilHTTPError
 */
export interface HttputilHTTPError {
    /**
     * 
     * @type {number}
     * @memberof HttputilHTTPError
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof HttputilHTTPError
     */
    message?: string;
}

/**
 * Check if a given object implements the HttputilHTTPError interface.
 */
export function instanceOfHttputilHTTPError(value: object): value is HttputilHTTPError {
    return true;
}

export function HttputilHTTPErrorFromJSON(json: any): HttputilHTTPError {
    return HttputilHTTPErrorFromJSONTyped(json, false);
}

export function HttputilHTTPErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): HttputilHTTPError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function HttputilHTTPErrorToJSON(json: any): HttputilHTTPError {
    return HttputilHTTPErrorToJSONTyped(json, false);
}

export function HttputilHTTPErrorToJSONTyped(value?: HttputilHTTPError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

