/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Example API
 * This is a sample server celler server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelAdmin
 */
export interface ModelAdmin {
    /**
     * 
     * @type {number}
     * @memberof ModelAdmin
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelAdmin
     */
    name?: string;
}

/**
 * Check if a given object implements the ModelAdmin interface.
 */
export function instanceOfModelAdmin(value: object): value is ModelAdmin {
    return true;
}

export function ModelAdminFromJSON(json: any): ModelAdmin {
    return ModelAdminFromJSONTyped(json, false);
}

export function ModelAdminFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelAdmin {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ModelAdminToJSON(json: any): ModelAdmin {
    return ModelAdminToJSONTyped(json, false);
}

export function ModelAdminToJSONTyped(value?: ModelAdmin | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

