/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Example API
 * This is a sample server celler server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelAccount
 */
export interface ModelAccount {
    /**
     * 
     * @type {number}
     * @memberof ModelAccount
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelAccount
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelAccount
     */
    uuid?: string;
}

/**
 * Check if a given object implements the ModelAccount interface.
 */
export function instanceOfModelAccount(value: object): value is ModelAccount {
    return true;
}

export function ModelAccountFromJSON(json: any): ModelAccount {
    return ModelAccountFromJSONTyped(json, false);
}

export function ModelAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
    };
}

export function ModelAccountToJSON(json: any): ModelAccount {
    return ModelAccountToJSONTyped(json, false);
}

export function ModelAccountToJSONTyped(value?: ModelAccount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'uuid': value['uuid'],
    };
}

