/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Example API
 * This is a sample server celler server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelUpdateAccount
 */
export interface ModelUpdateAccount {
    /**
     * 
     * @type {string}
     * @memberof ModelUpdateAccount
     */
    name?: string;
}

/**
 * Check if a given object implements the ModelUpdateAccount interface.
 */
export function instanceOfModelUpdateAccount(value: object): value is ModelUpdateAccount {
    return true;
}

export function ModelUpdateAccountFromJSON(json: any): ModelUpdateAccount {
    return ModelUpdateAccountFromJSONTyped(json, false);
}

export function ModelUpdateAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelUpdateAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ModelUpdateAccountToJSON(json: any): ModelUpdateAccount {
    return ModelUpdateAccountToJSONTyped(json, false);
}

export function ModelUpdateAccountToJSONTyped(value?: ModelUpdateAccount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

