/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Example API
 * This is a sample server celler server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelAccount } from './ModelAccount';
import {
    ModelAccountFromJSON,
    ModelAccountFromJSONTyped,
    ModelAccountToJSON,
    ModelAccountToJSONTyped,
} from './ModelAccount';

/**
 * 
 * @export
 * @interface ModelBottle
 */
export interface ModelBottle {
    /**
     * 
     * @type {ModelAccount}
     * @memberof ModelBottle
     */
    account?: ModelAccount;
    /**
     * 
     * @type {number}
     * @memberof ModelBottle
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelBottle
     */
    name?: string;
}

/**
 * Check if a given object implements the ModelBottle interface.
 */
export function instanceOfModelBottle(value: object): value is ModelBottle {
    return true;
}

export function ModelBottleFromJSON(json: any): ModelBottle {
    return ModelBottleFromJSONTyped(json, false);
}

export function ModelBottleFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelBottle {
    if (json == null) {
        return json;
    }
    return {
        
        'account': json['account'] == null ? undefined : ModelAccountFromJSON(json['account']),
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ModelBottleToJSON(json: any): ModelBottle {
    return ModelBottleToJSONTyped(json, false);
}

export function ModelBottleToJSONTyped(value?: ModelBottle | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account': ModelAccountToJSON(value['account']),
        'id': value['id'],
        'name': value['name'],
    };
}

