/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Example API
 * This is a sample server celler server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HttputilHTTPError,
  ModelAdmin,
} from '../models/index';
import {
    HttputilHTTPErrorFromJSON,
    HttputilHTTPErrorToJSON,
    ModelAdminFromJSON,
    ModelAdminToJSON,
} from '../models/index';

/**
 * 
 */
export class AdminApi extends runtime.BaseAPI {

    /**
     * get admin info
     * Auth admin
     */
    async adminAuthPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelAdmin>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }


        let urlPath = `/admin/auth`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelAdminFromJSON(jsonValue));
    }

    /**
     * get admin info
     * Auth admin
     */
    async adminAuthPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelAdmin> {
        const response = await this.adminAuthPostRaw(initOverrides);
        return await response.value();
    }

}
