/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Example API
 * This is a sample server celler server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HttputilHTTPError,
  ModelBottle,
} from '../models/index';
import {
    HttputilHTTPErrorFromJSON,
    HttputilHTTPErrorToJSON,
    ModelBottleFromJSON,
    ModelBottleToJSON,
} from '../models/index';

export interface GetStringByIntRequest {
    id: number;
}

/**
 * 
 */
export class BottlesApi extends runtime.BaseAPI {

    /**
     * get bottles
     * List bottles
     */
    async bottlesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ModelBottle>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/bottles`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ModelBottleFromJSON));
    }

    /**
     * get bottles
     * List bottles
     */
    async bottlesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ModelBottle>> {
        const response = await this.bottlesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * get string by ID
     * Show a bottle
     */
    async getStringByIntRaw(requestParameters: GetStringByIntRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelBottle>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getStringByInt().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/bottles/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelBottleFromJSON(jsonValue));
    }

    /**
     * get string by ID
     * Show a bottle
     */
    async getStringByInt(requestParameters: GetStringByIntRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelBottle> {
        const response = await this.getStringByIntRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
