/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Example API
 * This is a sample server celler server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ModelAccount,
} from '../models/index';
import {
    ModelAccountFromJSON,
    ModelAccountToJSON,
} from '../models/index';

export interface ExamplesPostPostRequest {
    message: ModelAccount;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * post request example
     * post request example
     */
    async examplesPostPostRaw(requestParameters: ExamplesPostPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['message'] == null) {
            throw new runtime.RequiredError(
                'message',
                'Required parameter "message" was null or undefined when calling examplesPostPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/examples/post`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ModelAccountToJSON(requestParameters['message']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * post request example
     * post request example
     */
    async examplesPostPost(requestParameters: ExamplesPostPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.examplesPostPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
